# Generated by Django 3.2.3 on 2021-05-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(default='Undefined', max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
