# Generated by Django 3.2.3 on 2021-05-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findprice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('undefined', 'UNDEFINED'), ('alimenti', 'ALIMENTI'), ('giocattoli', 'GIOCATTOLI'), ('elettronica', 'ELETTRONICA'), ('casa', 'CASA')], default='undefined', max_length=200),
        ),
    ]
