# Generated by Django 3.2.3 on 2021-06-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findprice', '0003_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='scan',
            name='long',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
    ]
