# Generated by Django 3.2.3 on 2021-06-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findprice', '0004_auto_20210607_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='scan_datatime',
            new_name='scan_time',
        ),
    ]
